In [9]:
import numpy as np
arr = np.array([[0, 1], [2, 3]])
print("Original flattened array:")
print(arr)
flat_arr = arr.flatten()
max_value = flat_arr.max()
min_value = flat_arr.min()
print("Maximum value of the above flattened array:", max_value)
print("Minimum value of the above flattened array:", min_value)


Original flattened array:
[[0 1]
 [2 3]]
Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [8]:
import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 matrix with values ranging from 2 to 10:")
print(matrix)


3x3 matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print("Original array:", arr)
float_arr = arr.astype(float)
print("Array converted to a float type:", float_arr)


Original array: [1 2 3 4]
Array converted to a float type: [1. 2. 3. 4.]


In [6]:
import numpy as np
A = np.array([[5, 5],
              [1, 2]])

B = np.array([[0, 1],
              [1, 0]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)
result = np.dot(A, B)

print("\nResultant Matrix after multiplication:")
print(result)
transpose_result = result.T

print("\nTranspose of the resultant matrix:")
print(transpose_result)


Matrix A:
[[5 5]
 [1 2]]

Matrix B:
[[0 1]
 [1 0]]

Resultant Matrix after multiplication:
[[5 5]
 [2 1]]

Transpose of the resultant matrix:
[[5 2]
 [5 1]]


In [5]:
import numpy as np
A = np.array([
    [6, 1, 1, 3],
    [4, 2, 5, 1],
    [2, 8, 7, 6],
    [3, 1, 9, 7]
], dtype=float)
print("Original matrix A:")
print(A)
det = np.linalg.det(A)
print("\nDeterminant of A:", det)
if abs(det) < 1e-12:
    print("Matrix is singular (determinant ≈ 0). Inverse does not exist.")
else:
    A_inv = np.linalg.inv(A)
    np.set_printoptions(precision=8, suppress=True)
    print("\nInverse of A (A^-1):")
    print(A_inv)


Original matrix A:
[[6. 1. 1. 3.]
 [4. 2. 5. 1.]
 [2. 8. 7. 6.]
 [3. 1. 9. 7.]]

Determinant of A: -1448.9999999999998

Inverse of A (A^-1):
[[ 0.13457557  0.09661836 -0.03588682 -0.04071774]
 [-0.00207039  0.02415459  0.13388544 -0.11732229]
 [-0.12836439  0.16425121 -0.03243616  0.05935128]
 [ 0.10766046 -0.25603865  0.03795721  0.10075914]]
